import Foundation
import OSLog

extension NotifiableIntelligence {
    /// Hard suppression window — see PRD §4.4.
    static let hardSuppressionWindow: TimeInterval = 120

    /// JSON shape hint appended to the model context when the caller requests
    /// an `AlertDecision`. Without this, the model invents its own key names
    /// and decoding fails.
    static let alertDecisionResponseShape = """
    <response_shape>
    Return ONLY a JSON object with this exact shape. Use null for fields that don't apply.
    {
      "shouldAlert": <true | false>,
      "candidateId": <string | null>,
      "headline": <string up to 60 characters | null>,
      "body": <string up to 120 characters | null>,
      "priority": <"low" | "medium" | "high">,
      "suppressFor": <number of seconds, 0 to 86400 | null>
    }

    If shouldAlert is false, candidateId / headline / body may be null.
    If shouldAlert is true, candidateId / headline / body must be non-null strings.
    Do not wrap the JSON in code fences or any other text.
    </response_shape>
    """

    /// Top-level orchestrator. Owns a ``PreferenceStore`` and a
    /// ``ModelAdapter``, and exposes the ``decide(domain:candidates:schema:options:)``
    /// entry point.
    public final class Engine: Sendable {
        public let preferences: any PreferenceStore
        let adapter: any ModelAdapter
        let clock: any Clock<Duration>
        let assembler: ContextAssembler
        private let log = Logger(subsystem: "com.futureworkshops.notifiable-ai.intelligence", category: "decide")

        public init(
            store: any PreferenceStore,
            adapter: any ModelAdapter,
            clock: any Clock<Duration> = ContinuousClock()
        ) {
            self.preferences = store
            self.adapter = adapter
            self.clock = clock
            self.assembler = ContextAssembler()
        }

        /// Decide whether to surface an alert for one of the supplied
        /// `candidates`. The Intelligence layer pulls preferences for the
        /// domain, recent alert history, assembles an XML context block,
        /// calls the on-device LLM, validates the result, and records the
        /// alert if `shouldAlert == true`.
        ///
        /// Usage:
        /// ```swift
        /// let decision = try await engine.decide(
        ///     domain: "demo.alerts",
        ///     candidates: candidates,
        ///     schema: NotifiableIntelligence.AlertDecision.self
        /// )
        /// ```
        ///
        /// - Parameter domain: namespace identifier for preferences and history.
        /// - Parameter candidates: events generated by the host app.
        /// - Parameter schema: a `Decodable` type the model should target.
        /// - Parameter options: per-call overrides.
        /// - Throws: ``NotifiableIntelligenceError`` on validation, store, or
        ///   model failures.
        public func decide<Schema: Decodable & Sendable>(
            domain: String,
            candidates: [CandidateEvent],
            schema: Schema.Type,
            options: DecideOptions = .init()
        ) async throws -> Schema {
            log.info("decide.start domain=\(domain, privacy: .public) candidates=\(candidates.count, privacy: .public)")

            let prefs: [Preference]
            let recentAlerts: [RecordedAlert]
            do {
                prefs = try await preferences.all(domain: domain)
                recentAlerts = try await preferences.recentAlerts(domain: domain, within: 3_600)
            } catch let e as NotifiableIntelligenceError {
                throw e
            } catch {
                throw NotifiableIntelligenceError.storeUnavailable(underlying: error)
            }

            let assembled = assembler.assemble(
                domain: domain,
                preferences: prefs,
                candidates: candidates,
                recentAlerts: recentAlerts,
                budget: options.tokenBudget,
                includeDecayed: options.includeDecayedPreferences
            )
            log.info("decide.context_assembled tokens=\(assembled.estimatedTokens, privacy: .public) dropped=\(assembled.droppedPreferences.count, privacy: .public)")

            let modelOptions = ModelOptions(temperature: options.temperature, maxOutputTokens: 256)
            let systemPrompt = options.systemPromptOverride ?? SystemPrompts.decideAlert

            // Append a JSON-shape hint when we know the schema. Foundation
            // Models has no schema awareness for plain Codable types, so
            // without this the model invents its own keys and decoding fails.
            let contextWithShape: String
            if schema is AlertDecision.Type {
                contextWithShape = assembled.xml + "\n\n" + NotifiableIntelligence.alertDecisionResponseShape
            } else {
                contextWithShape = assembled.xml
            }

            let started = Date()
            let raw = try await adapter.decide(
                systemPrompt: systemPrompt,
                contextBlock: contextWithShape,
                schema: schema,
                options: modelOptions
            )
            let latencyMs = Int(Date().timeIntervalSince(started) * 1_000)
            log.info("decide.model_call latencyMs=\(latencyMs, privacy: .public)")

            // Apply AlertDecision-specific validation + suppression rail.
            if let decoded = raw as? AlertDecision {
                let validated = try decoded.validate(truncating: { [weak self] original, truncated in
                    self?.log.warning("decide.truncated original.count=\(original.count, privacy: .public) → \(truncated.count, privacy: .public)")
                })

                let final: AlertDecision
                if validated.shouldAlert,
                   let cid = validated.candidateId,
                   let matched = candidates.first(where: { $0.id == cid }) {
                    let recent = (try? await preferences.recentAlerts(domain: domain, within: NotifiableIntelligence.hardSuppressionWindow)) ?? []
                    let suppress = recent.contains { $0.subject == matched.subject }
                    if suppress {
                        log.notice("decide.suppressed subject=\(matched.subject, privacy: .public)")
                        final = AlertDecision(
                            shouldAlert: false,
                            candidateId: validated.candidateId,
                            headline: validated.headline,
                            body: validated.body,
                            priority: validated.priority,
                            suppressFor: validated.suppressFor
                        )
                    } else {
                        final = validated
                        let alert = RecordedAlert(
                            domain: domain,
                            subject: matched.subject,
                            type: matched.type,
                            shownAt: Date()
                        )
                        do {
                            try await preferences.recordAlert(alert)
                        } catch {
                            throw NotifiableIntelligenceError.storeUnavailable(underlying: error)
                        }
                    }
                } else {
                    final = validated
                }

                log.info("decide.complete shouldAlert=\(final.shouldAlert, privacy: .public)")
                // Safe force-cast: we only entered this branch because Schema == AlertDecision.
                return final as! Schema
            }

            log.info("decide.complete shouldAlert=n/a custom_schema=\(String(describing: schema), privacy: .public)")
            return raw
        }
    }
}
